-- Criação do banco de dados
CREATE DATABASE DBTREINAMENTOS;
GO

USE DBTREINAMENTOS;
GO

-- Criação da tabela TBCENTROCUSTO
CREATE TABLE [dbo].[TBCENTROCUSTO] (
    [ID_CENTRODECUSTO]   INT           IDENTITY (1, 1) NOT NULL,
    [NOME_CENTRODECUSTO] NVARCHAR (50) NOT NULL,
    [CODIGO_OBRA]        INT           NULL,
    CONSTRAINT [PK_TBCENTROCUSTO] PRIMARY KEY CLUSTERED ([ID_CENTRODECUSTO] ASC)
);

-- Criação da tabela TBDEPARTAMENTO
CREATE TABLE [dbo].[TBDEPARTAMENTO] (
    [ID_DEPARTAMENTO]   INT           IDENTITY (1, 1) NOT NULL,
    [NOME_DEPARTAMENTO] NVARCHAR (50) NOT NULL,
    [ID_CENTRODECUSTO]  INT           NULL,
    CONSTRAINT [PK_TBDEPARTAMENTO] PRIMARY KEY CLUSTERED ([ID_DEPARTAMENTO] ASC),
    CONSTRAINT [FK_TBDEPARTAMENTO_TBCENTROCUSTO] FOREIGN KEY ([ID_CENTRODECUSTO]) REFERENCES [dbo].[TBCENTROCUSTO] ([ID_CENTRODECUSTO])
);

-- Criação da tabela TBCARGO
CREATE TABLE [dbo].[TBCARGO] (
    [ID_CARGO]   INT            IDENTITY (1, 1) NOT NULL,
    [NOME_CARGO] NVARCHAR (50)  NOT NULL,
    [DESCRICAO]  NVARCHAR (255) NULL,
    CONSTRAINT [PK_TBCARGO] PRIMARY KEY CLUSTERED ([ID_CARGO] ASC)
);

-- Criação da tabela TBCOLABORADOR
CREATE TABLE [dbo].[TBCOLABORADOR] (
    [ID_COLABORADOR]   INT           IDENTITY (1, 1) NOT NULL,
    [CPF]              CHAR (14)     NOT NULL,
    [MATRICULA]        INT           NOT NULL,
    [NOME_COLABORADOR] NVARCHAR (50) NOT NULL,
    [DATA_ADMISSAO]    DATE          NULL,
    [STATUS]           BIT           NOT NULL,
    [REGIME_TRABALHO]  NVARCHAR (50) NULL,
    [CARGO_GESTAO]     BIT           NULL,
    [ID_CARGO]         INT           NOT NULL,
    [ID_DEPARTAMENTO]  INT           NOT NULL,
    CONSTRAINT [PK_TBCOLABORADOR] PRIMARY KEY CLUSTERED ([ID_COLABORADOR] ASC),
    CONSTRAINT [FK_TBCOLABORADOR_TBCARGO] FOREIGN KEY ([ID_CARGO]) REFERENCES [dbo].[TBCARGO] ([ID_CARGO]),
    CONSTRAINT [FK_TBCOLABORADOR_TBDEPARTAMENTO] FOREIGN KEY ([ID_DEPARTAMENTO]) REFERENCES [dbo].[TBDEPARTAMENTO] ([ID_DEPARTAMENTO])
);

-- Criação da tabela TBTREINAMENTO
CREATE TABLE [dbo].[TBTREINAMENTO] (
    [ID_TREINAMENTO]   INT            IDENTITY (1, 1) NOT NULL,
    [NOME_TREINAMENTO] NVARCHAR (150) NOT NULL,
    [DESCRICAO]        NVARCHAR (255) NULL,
    [CARGA_HORARIA]    INT            NULL,
    [FREQUENCIA]       NVARCHAR (50)  NULL,
    [ID_DEPARTAMENTO]  INT            NOT NULL,
    CONSTRAINT [PK_TBTREINAMENTO] PRIMARY KEY CLUSTERED ([ID_TREINAMENTO] ASC),
    CONSTRAINT [FK_TBTREINAMENTO_TBDEPARTAMENTO] FOREIGN KEY ([ID_DEPARTAMENTO]) REFERENCES [dbo].[TBDEPARTAMENTO] ([ID_DEPARTAMENTO])
);

-- Criação da tabela TBTREINA_CARGO
CREATE TABLE [dbo].[TBTREINA_CARGO] (
    [ID_TREINACARGO] INT IDENTITY (1, 1) NOT NULL,
    [ID_CARGO]       INT NOT NULL,
    [ID_TREINAMENTO] INT NOT NULL,
    CONSTRAINT [PK_TBTREINA_CARGO] PRIMARY KEY CLUSTERED ([ID_TREINACARGO] ASC),
    CONSTRAINT [FK_TBTREINA_CARGO_TBCARGO] FOREIGN KEY ([ID_CARGO]) REFERENCES [dbo].[TBCARGO] ([ID_CARGO]),
    CONSTRAINT [FK_TBTREINA_CARGO_TBTREINAMENTO] FOREIGN KEY ([ID_TREINAMENTO]) REFERENCES [dbo].[TBTREINAMENTO] ([ID_TREINAMENTO])
);

-- Criação da tabela TBTREINA_COLABORADOR
CREATE TABLE [dbo].[TBTREINA_COLABORADOR] (
    [ID_TREINACOLABORADOR] INT           IDENTITY (1, 1) NOT NULL,
    [ID_COLABORADOR]       INT           NOT NULL,
    [ID_TREINAMENTO]       INT           NOT NULL,
    [DATA_TREINAMENTO]     DATE          NOT NULL,
    [VALIDADE_TREINAMENTO] BIT           NOT NULL,
    [DATA_VALIDADE]        DATE          NULL,
    [STATUS]               NVARCHAR (50) NULL,
    [NECESSIDADE]          NVARCHAR (50) NULL,
    CONSTRAINT [PK_TBTREINA_COLABORADOR] PRIMARY KEY CLUSTERED ([ID_TREINACOLABORADOR] ASC),
    CONSTRAINT [FK_TBTREINA_COLABORADOR_TBCOLABORADOR] FOREIGN KEY ([ID_COLABORADOR]) REFERENCES [dbo].[TBCOLABORADOR] ([ID_COLABORADOR]),
    CONSTRAINT [FK_TBTREINA_COLABORADOR_TBTREINAMENTO] FOREIGN KEY ([ID_TREINAMENTO]) REFERENCES [dbo].[TBTREINAMENTO] ([ID_TREINAMENTO])
);


